# digio.cmd generated by gen_digio.pl
# CP_NCMDS = 50
# CP_DS    = 104
# PB_S     = 160
%INTERFACE <dccc:dccc>
&off_on <int>
  : Off { $0 = 1; }
  : On { $0 = 0; } 
  ;
&command
  : &dccc_cmd &off_on * { if_dccc.Turf("D%d\n", $1*2 + $2); }
  ;
&dccc_cmd <int>
# : Command 0 { $0 = 0; }
# : Command 1 { $0 = 1; }
# : Command 2 { $0 = 2; }
# : Command 3 { $0 = 3; }
# : Command 4 { $0 = 4; }
# : Command 5 { $0 = 5; }
# : Command 6 { $0 = 6; }
# : Command 7 { $0 = 7; }
# : Command 8 { $0 = 8; }
# : Command 9 { $0 = 9; }
# : Command 10 { $0 = 10; }
# : Command 11 { $0 = 11; }
# : Command 12 { $0 = 12; }
# : Command 13 { $0 = 13; }
# : Command 14 { $0 = 14; }
# : Command 15 { $0 = 15; }
# : Command 16 { $0 = 16; }
# : Command 17 { $0 = 17; }
# : Command 18 { $0 = 18; }
# : Command 19 { $0 = 19; }
# : Command 20 { $0 = 20; }
# : Command 21 { $0 = 21; }
# : Command 22 { $0 = 22; }
# : Command 23 { $0 = 23; }
# : Command 24 { $0 = 24; }
# : Command 25 { $0 = 25; }
# : Command 26 { $0 = 26; }
# : Command 27 { $0 = 27; }
# : Command 28 { $0 = 28; }
# : Command 29 { $0 = 29; }
# : Command 30 { $0 = 30; }
# : Command 31 { $0 = 31; }
  : Command QCLI Reset { $0 = 32; }
# : Command 33 { $0 = 33; }
# : Command 34 { $0 = 34; }
# : Command 35 { $0 = 35; }
  : Command Exhaust Valve { $0 = 36; }
# : Command 37 { $0 = 37; }
# : Command 38 { $0 = 38; }
# : Command 39 { $0 = 39; }
# : Command 40 { $0 = 40; }
# : Command 41 { $0 = 41; }
# : Command 42 { $0 = 42; }
# : Command 43 { $0 = 43; }
# : Command 44 { $0 = 44; }
# : Command 45 { $0 = 45; }
# : Command 46 { $0 = 46; }
# : Command 47 { $0 = 47; }
# : Command 48 { $0 = 48; }
# : Command 49 { $0 = 49; }
  ;
