# digio.cmd generated by gen_digio.pl
# CP_NCMDS = 50
# CP_DS    = 104
# PB_S     = 160
%INTERFACE <dccc:dccc>
&off_on <int>
  : Off { $0 = 1; }
  : On { $0 = 0; } 
  ;
&command
  : Command &dccc_cmd &off_on * { if_dccc.Turf("D%d\n", $2*2 + $3); }
  ;
&dccc_cmd <int>
  : QCLI Reset { $0 = 0; }
  : Exhaust Valve { $0 = 1; }
  : Gas Deck Valve { $0 = 2; }
  : Cal Gas Valve { $0 = 3; }
# : 4 { $0 = 4; }
# : 5 { $0 = 5; }
# : 6 { $0 = 6; }
# : 7 { $0 = 7; }
  ;
