# Invoking: appgen_module TMbase X 
# Invoking: appgen_module QCLI X 
# Makefile Generated Thu Oct 13 13:43:48 EDT 2016
MNC=HCl
SPECFILE=HCl.spec
PCMFILE=HCl.pcm
SRC=base.tmc PTRH.tmc /usr/local/share/huarp/ptrhm.cc T30K75KU.tmc
SRC+=temps.tmc TS_T_t_cal.tmc SWData.tmc SWData.h
SRC+=/usr/local/share/huarp/tdrift.tmc
SRC+=/usr/local/share/huarp/cpu_usage.tmc
SRC+=/usr/local/share/huarp/tmdf.tmc freemem.tmc
SRC+=/usr/local/share/huarp/flttime.tmc
SRC+=/usr/local/share/huarp/qcli_types.tmc QCLI.tmc waves.tmc
SRC+=AI_col.tmc PTRH_col.tmc /usr/local/share/huarp/ptrhm_col.cc
SRC+=temps_col.tmc SWData_col.tmc
SRC+=/usr/local/share/huarp/tdrift_col.tmc
SRC+=/usr/local/share/huarp/cpu_usage_col.tmc
SRC+=/usr/local/share/huarp/tmdf_col.tmc
SRC+=/usr/local/share/huarp/freemem_col.tmc QCLI_col.tmc -lsubbus
SRC+=/usr/local/share/huarp/root.cmd /usr/local/share/huarp/phrtg.cmd
SRC+=ao.cmd address.h SWData.cmd /usr/local/share/huarp/getcon.cmd
SRC+=/usr/local/share/huarp/qclia.cmd QCLI.cmd waves.cmd
SRC+=QCLI_conv.tmc PTRH_conv.tmc temps_conv.tmc HCl.tbl rtg.tmc
SRC+=/usr/local/share/oui/cic.oui TS.tbl HCl.tma HCl.sws HCl.doit
SRC+=HCl.genui TMbase.genui QCLI.genui HCl.pcm
TOOL=HCl.spec Makefile
SCRIPT=interact digio.dccc
OBJ=waves.cmd waves.out waves.tmc waves.m waves.log HClcol.cc tm.dac
OBJ+=HClcoloui.c HClcoloui.o HClcol.o ptrhm.o ptrhm_col.o HClcmd.cc
OBJ+=HClcmd.dat HClsrvr.o HClsrvroui.c HClsrvroui.o HCltbl.tmc
OBJ+=TStbl.tmc HCldisp.cc HCldispoui.c HCldispoui.o HCldisp.o
OBJ+=HCltblnc.tmc TStblnc.tmc HCldispnc.cc HCldispncoui.c
OBJ+=HCldispncoui.o HCldispnc.o HClsws.tma HClalgoa.tmc HClalgo.cc
OBJ+=HClalgooui.c HClalgooui.o HClalgo.o doit.dep HClclt.o
OBJ+=HClcltoui.c HClcltoui.o HClcltnc.o HClcltncoui.c HClcltncoui.o
OBJ+=HClengext.cdf HClengextcdf.oui HClengextcdf.tmc HClengext.cc
OBJ+=HClengextoui.c HClengextoui.o HClengext.o HCltbl.tmc.dep
OBJ+=TStbl.tmc.dep HCltblnc.tmc.dep TStblnc.tmc.dep
TGT=HClcol HClsrvr HCldisp HCldispnc HClalgo doit HClclt HClcltnc
TGT+=HClengext
DISTRIB=waves.out HCl.pcm tm.dac
IDISTRIB=Experiment.config VERSION doit
SRCDIST=waves.m waves.qcli HCl.tbl TS.tbl HCl.tma base.tmc PTRH.tmc
SRCDIST+=/usr/local/share/huarp/ptrhm.cc T30K75KU.tmc temps.tmc
SRCDIST+=TS_T_t_cal.tmc SWData.tmc SWData.h
SRCDIST+=/usr/local/share/huarp/tdrift.tmc
SRCDIST+=/usr/local/share/huarp/cpu_usage.tmc
SRCDIST+=/usr/local/share/huarp/tmdf.tmc freemem.tmc
SRCDIST+=/usr/local/share/huarp/flttime.tmc
SRCDIST+=/usr/local/share/huarp/qcli_types.tmc QCLI.tmc waves.tmc
TMCBASE=base.tmc PTRH.tmc /usr/local/share/huarp/ptrhm.cc
TMCBASE+=T30K75KU.tmc temps.tmc TS_T_t_cal.tmc SWData.tmc SWData.h
TMCBASE+=/usr/local/share/huarp/tdrift.tmc
TMCBASE+=/usr/local/share/huarp/cpu_usage.tmc
TMCBASE+=/usr/local/share/huarp/tmdf.tmc freemem.tmc
TMCBASE+=/usr/local/share/huarp/flttime.tmc
TMCBASE+=/usr/local/share/huarp/qcli_types.tmc QCLI.tmc waves.tmc
CMDBASE=/usr/local/share/huarp/root.cmd
CMDBASE+=/usr/local/share/huarp/phrtg.cmd ao.cmd address.h SWData.cmd
CMDBASE+=SWData.h /usr/local/share/huarp/getcon.cmd
CMDBASE+=/usr/local/share/huarp/qclia.cmd QCLI.cmd waves.cmd
COLBASE=AI_col.tmc PTRH_col.tmc /usr/local/share/huarp/ptrhm_col.cc
COLBASE+=temps_col.tmc SWData_col.tmc
COLBASE+=/usr/local/share/huarp/tdrift_col.tmc
COLBASE+=/usr/local/share/huarp/cpu_usage_col.tmc
COLBASE+=/usr/local/share/huarp/tmdf_col.tmc
COLBASE+=/usr/local/share/huarp/freemem_col.tmc QCLI_col.tmc
SWSBASE=HCl.sws
QCLIBASE=waves.qcli
GENUIBASE=HCl.genui TMbase.genui QCLI.genui
EXTBASE=QCLI_conv.tmc
SPECDEPBASE=/usr/local/share/huarp/TMbase.agm
SPECDEPBASE+=/usr/local/share/huarp/freemem_def.tmc.in
SPECDEPBASE+=/usr/local/share/huarp/TMbase.genui.in
SPECDEPBASE+=/usr/local/share/huarp/TMbase.tbl.in
SPECDEPBASE+=/usr/local/share/huarp/QCLI.agm
SPECDEPBASE+=/usr/local/share/huarp/qcli.tmc.in
SPECDEPBASE+=/usr/local/share/huarp/qcli_col.tmc.in
SPECDEPBASE+=/usr/local/share/huarp/qclis.cmd.in
SPECDEPBASE+=/usr/local/share/huarp/qcli_conv.tmc.in
SPECDEPBASE+=/usr/local/share/huarp/qcli.genui.in
SPECDEPBASE+=/usr/local/share/huarp/qcli.tbl.in
AG_CPPFLAGS=
PHTGT=HCltbl.tmc TStbl.tmc
SOURCE=$(SRC) $(TOOL) $(SCRIPT)
OBJECT=$(OBJ) *.err
TARGET=$(TGT)
DSTRB=$(TGT) $(DISTRIB) $(SCRIPT)
TGTDIR= $(TGTNODE)/home/hcl16
include /usr/local/share/huarp/appgen.mk

.PHONY : all all-dist extdistribution distribution clean clean-dist check_photon

IGNOREFILE=.gitignore
all : Makefile check_photon $(TGT) $(IGNOREFILE)
all-dist : $(DSTRB) $(SRCDIST) VERSION
Makefile : HCl.spec $(SPECDEPBASE)
	appgen HCl.spec
VERSION=`cat VERSION`
extdistribution : $(DSTRB) $(SRCDIST) VERSION
	@[ -d $(TGTDIR)/bin ] || mkdir $(TGTDIR)/bin
	@[ -d $(TGTDIR)/bin/$(VERSION) ] || mkdir $(TGTDIR)/bin/$(VERSION)
	@[ -d $(TGTDIR)/bin/$(VERSION)/Base ] || mkdir $(TGTDIR)/bin/$(VERSION)/Base
	@[ ! -f $(TGTDIR)/bin/$(VERSION)/$(PCMFILE) ] || \
	  cmp -s $(TGTDIR)/bin/$(VERSION)/$(PCMFILE) $(PCMFILE) || \
	  ( echo "$(PCMFILE) changed without VERSION update"; false )
	@distribute $(FORCE) $(TGTDIR)/bin/$(VERSION) $(DSTRB)
	@distribute $(FORCE) $(TGTDIR)/bin/$(VERSION)/Base $(SRCDIST)
distribution : extdistribution
	@distribute $(FORCE) $(TGTDIR) $(IDISTRIB)
check_photon :
ifeq ($(WPHOTON),YES)
	@for tgt in $(PHTGT); do \
	  cmp -s $$tgt /usr/local/share/huarp/nulltbl.tmc && echo Remaking $$tgt && rm -f $$tgt; \
	done; true
endif
HClcol : HClcol.o ptrhm.o ptrhm_col.o HClcoloui.o
	$(LINK.privCXX) HClcol.o ptrhm.o ptrhm_col.o HClcoloui.o -lsubbus -ltmpp -ltm -lnort
	$(OUIUSE) HClcoloui.c
	$(PROMOTE) HClcol
HClsrvr : HClsrvr.o HClsrvroui.o
	$(LINK.privCXX) HClsrvr.o HClsrvroui.o -lsubbus -ltmpp -ltm -lnort
	$(OUIUSE) HClsrvroui.c
	$(PROMOTE) HClsrvr
HCldisp : HCldisp.o ptrhm.o HCldispoui.o
	$(LINK.normCXX) HCldisp.o ptrhm.o HCldispoui.o -ldisp -ltmph -lph -ltmpp -ltm -lnort
	$(OUIUSE) HCldispoui.c
HCldispnc : HCldispnc.o ptrhm.o HCldispncoui.o
	$(LINK.normCXX) HCldispnc.o ptrhm.o HCldispncoui.o -ldispnc -ltmnc -lncurses -ltmpp -ltm -lnort
	$(OUIUSE) HCldispncoui.c
HClalgo : HClalgo.o ptrhm.o HClalgooui.o
	$(LINK.normCXX) HClalgo.o ptrhm.o HClalgooui.o -ltmpp -ltm -lnort
	$(OUIUSE) HClalgooui.c
doit : HCl.doit
	mkdoit3 -o doit  HCl.doit
HClclt : HClclt.o HClcltoui.o
	$(LINK.normCXX) HClclt.o HClcltoui.o -ltmph -lph -ltmpp -ltm -lnort
	$(OUIUSE) HClcltoui.c
HClcltnc : HClcltnc.o HClcltncoui.o
	$(LINK.normCXX) HClcltnc.o HClcltncoui.o -ltmnc -lncurses -ltmpp -ltm -lnort
	$(OUIUSE) HClcltncoui.c
HClengext : HClengext.o ptrhm.o HClengextoui.o
	$(LINK.normCXX) HClengext.o ptrhm.o HClengextoui.o -ltmpp -ltm -lnort
	$(OUIUSE) HClengextoui.c
HClcol.cc : base.tmc PTRH.tmc T30K75KU.tmc temps.tmc TS_T_t_cal.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc /usr/local/share/huarp/qcli_types.tmc QCLI.tmc waves.tmc AI_col.tmc PTRH_col.tmc temps_col.tmc SWData_col.tmc /usr/local/share/huarp/tdrift_col.tmc /usr/local/share/huarp/cpu_usage_col.tmc /usr/local/share/huarp/tmdf_col.tmc /usr/local/share/huarp/freemem_col.tmc QCLI_col.tmc VERSION
	$(TMC.col) base.tmc PTRH.tmc T30K75KU.tmc temps.tmc TS_T_t_cal.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc /usr/local/share/huarp/qcli_types.tmc QCLI.tmc waves.tmc AI_col.tmc PTRH_col.tmc temps_col.tmc SWData_col.tmc /usr/local/share/huarp/tdrift_col.tmc /usr/local/share/huarp/cpu_usage_col.tmc /usr/local/share/huarp/tmdf_col.tmc /usr/local/share/huarp/freemem_col.tmc QCLI_col.tmc
HClcoloui.c : $(OUIDIR)/collect.oui $(OUIDIR)/seteuid.oui $(OUIDIR)/subbus.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/collect.oui $(OUIDIR)/seteuid.oui $(OUIDIR)/subbus.oui $(OUIDIR)/msg.oui
HClcoloui.o : HClcoloui.c SWData.h
HClcol.o : HClcol.cc SWData.h
ptrhm.o : /usr/local/share/huarp/ptrhm.cc SWData.h
	$(COMPILE.cc) /usr/local/share/huarp/ptrhm.cc
ptrhm_col.o : /usr/local/share/huarp/ptrhm_col.cc SWData.h
	$(COMPILE.cc) /usr/local/share/huarp/ptrhm_col.cc
HClcmd.cc : /usr/local/share/huarp/root.cmd /usr/local/share/huarp/phrtg.cmd ao.cmd SWData.cmd /usr/local/share/huarp/getcon.cmd /usr/local/share/huarp/qclia.cmd QCLI.cmd waves.cmd
	$(CMDGEN) -d HClcmd.dat /usr/local/share/huarp/root.cmd /usr/local/share/huarp/phrtg.cmd ao.cmd SWData.cmd /usr/local/share/huarp/getcon.cmd /usr/local/share/huarp/qclia.cmd QCLI.cmd waves.cmd
HClsrvr.o : HClcmd.cc address.h SWData.h
	$(COMPILE.srvr) HClcmd.cc
HClsrvroui.c : $(OUIDIR)/cis.oui $(OUIDIR)/seteuid.oui $(OUIDIR)/subbus.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/cis.oui $(OUIDIR)/seteuid.oui $(OUIDIR)/subbus.oui $(OUIDIR)/msg.oui
HClsrvroui.o : HClsrvroui.c address.h SWData.h
HCltbl.tmc : HCl.tbl
-include HCltbl.tmc.dep
TStbl.tmc : TS.tbl
-include TStbl.tmc.dep
HCldisp.cc : base.tmc PTRH.tmc T30K75KU.tmc temps.tmc TS_T_t_cal.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc /usr/local/share/huarp/qcli_types.tmc QCLI.tmc waves.tmc QCLI_conv.tmc PTRH_conv.tmc temps_conv.tmc HCltbl.tmc rtg.tmc TStbl.tmc VERSION
	$(TMC) base.tmc PTRH.tmc T30K75KU.tmc temps.tmc TS_T_t_cal.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc /usr/local/share/huarp/qcli_types.tmc QCLI.tmc waves.tmc QCLI_conv.tmc PTRH_conv.tmc temps_conv.tmc HCltbl.tmc rtg.tmc TStbl.tmc
HCldispoui.c : /usr/local/share/oui/cic.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) /usr/local/share/oui/cic.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
HCldispoui.o : HCldispoui.c SWData.h
HCldisp.o : HCldisp.cc SWData.h
HCltblnc.tmc : HCl.tbl
-include HCltblnc.tmc.dep
TStblnc.tmc : TS.tbl
-include TStblnc.tmc.dep
HCldispnc.cc : base.tmc PTRH.tmc T30K75KU.tmc temps.tmc TS_T_t_cal.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc /usr/local/share/huarp/qcli_types.tmc QCLI.tmc waves.tmc QCLI_conv.tmc PTRH_conv.tmc temps_conv.tmc HCltblnc.tmc rtg.tmc TStblnc.tmc VERSION
	$(TMC) base.tmc PTRH.tmc T30K75KU.tmc temps.tmc TS_T_t_cal.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc /usr/local/share/huarp/qcli_types.tmc QCLI.tmc waves.tmc QCLI_conv.tmc PTRH_conv.tmc temps_conv.tmc HCltblnc.tmc rtg.tmc TStblnc.tmc
HCldispncoui.c : /usr/local/share/oui/cic.oui $(OUIDIR)/nctable.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) /usr/local/share/oui/cic.oui $(OUIDIR)/nctable.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
HCldispncoui.o : HCldispncoui.c SWData.h
HCldispnc.o : HCldispnc.cc SWData.h
HClsws.tma : HCl.sws
	$(COMPILE.sws) HCl.sws
HClalgoa.tmc : HCl.tma HClsws.tma HClsrvr
	$(SERVER) ./HClsrvr
	$(TMCALGO) -V "`./HClsrvr -R`" HCl.tma HClsws.tma
HClalgo.cc : base.tmc PTRH.tmc T30K75KU.tmc temps.tmc TS_T_t_cal.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc /usr/local/share/huarp/qcli_types.tmc QCLI.tmc waves.tmc HClalgoa.tmc VERSION
	$(TMC) base.tmc PTRH.tmc T30K75KU.tmc temps.tmc TS_T_t_cal.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc /usr/local/share/huarp/qcli_types.tmc QCLI.tmc waves.tmc HClalgoa.tmc
HClalgooui.c : $(OUIDIR)/tma.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/tma.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
HClalgooui.o : HClalgooui.c SWData.h
HClalgo.o : HClalgo.cc SWData.h
doit.dep : HCl.doit
	mkdoit3 -M -o doit  HCl.doit
-include doit.dep
HClclt.o : HClcmd.cc address.h SWData.h
	$(COMPILE.clt) HClcmd.cc
HClcltoui.c : $(OUIDIR)/kbdclt.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/kbdclt.oui $(OUIDIR)/msg.oui
HClcltoui.o : HClcltoui.c address.h SWData.h
HClcltnc.o : HClcmd.cc address.h SWData.h
	$(COMPILE.cltnc) HClcmd.cc
HClcltncoui.c : $(OUIDIR)/kbdclt.oui $(OUIDIR)/nctable.oui $(OUIDIR)/msg.oui
	$(OUI) $(OUIDIR)/kbdclt.oui $(OUIDIR)/nctable.oui $(OUIDIR)/msg.oui
HClcltncoui.o : HClcltncoui.c address.h SWData.h
HClengext.cdf : HCl.genui TMbase.genui QCLI.genui
	$(GENUI2ENG) HCl.genui TMbase.genui QCLI.genui
HClengextcdf.oui : HClengext.cdf
	$(EDF2OUI) HClengext.cdf
HClengextcdf.tmc : HClengext.cdf
	$(EDF2EXT) HClengext.cdf
HClengext.cc : base.tmc PTRH.tmc T30K75KU.tmc temps.tmc TS_T_t_cal.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc /usr/local/share/huarp/qcli_types.tmc QCLI.tmc waves.tmc QCLI_conv.tmc HClengextcdf.tmc VERSION
	$(TMC) base.tmc PTRH.tmc T30K75KU.tmc temps.tmc TS_T_t_cal.tmc SWData.tmc /usr/local/share/huarp/tdrift.tmc /usr/local/share/huarp/cpu_usage.tmc /usr/local/share/huarp/tmdf.tmc freemem.tmc /usr/local/share/huarp/flttime.tmc /usr/local/share/huarp/qcli_types.tmc QCLI.tmc waves.tmc QCLI_conv.tmc HClengextcdf.tmc
HClengextoui.c : HClengextcdf.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
	$(OUI) HClengextcdf.oui $(OUIDIR)/dc.oui $(OUIDIR)/msg.oui
HClengextoui.o : HClengextoui.c SWData.h
HClengext.o : HClengext.cc SWData.h
SWData.h SWData.tmc SWData_col.tmc SWData.cmd :  HCl.sws
	swscomp -o SWData  HCl.sws
waves.cmd waves.out waves.tmc waves.m : waves.qcli
	qclicomp -o waves.out -c waves.cmd -d waves.tmc \
	  -v waves.log -m waves.m waves.qcli || \
	  ( rm -f waves.out waves.cmd waves.tmc waves.log waves.m; false )

tidy :
	rm -f $(OBJECT)
clean : tidy
	rm -f $(TARGET)
clean-dist : clean
$(IGNOREFILE) : Makefile
	@for i in $(OBJECT) $(TARGET); do echo "$$i"; done >$(IGNOREFILE)
COLFLAGS = -Haddress.h
address.h : HClcol.cc
