function phcl16tr(varargin);
% phcl16tr( [...] );
% Temps Rovers
h = timeplot({'Rov1T','Rov2T','Rov3T','Rov4T','Rov5T','Rov6T'}, ...
      'Temps Rovers', ...
      'Rovers', ...
      {'Rov1T','Rov2T','Rov3T','Rov4T','Rov5T','Rov6T'}, ...
      varargin{:} );
