function phcl16powers(varargin);
% phcl16powers( [...] );
% Power Status
h = ne_dstat({
  'PM0I1S', 'PM0Stat', 0; ...
	'PM0I2S', 'PM0Stat', 2; ...
	'PM0TOS', 'PM0Stat', 4; ...
	'PM0V1S', 'PM0Stat', 1; ...
	'PM0V2S', 'PM0Stat', 3; ...
	'PM1TOS', 'PM1Stat', 4; ...
	'PmpsIS', 'PM1Stat', 0; ...
	'PmpsVS', 'PM1Stat', 1; ...
	'Pmps2IS', 'PM1Stat', 2; ...
	'Pmps2VS', 'PM1Stat', 3 }, 'Status', varargin{:} );
