function phcl16thb(varargin);
% phcl16thb( [...] );
% Temps Heater Block
h = timeplot({'IHeatBlkT','IHeatBlkTSt'}, ...
      'Temps Heater Block', ...
      'Heater Block', ...
      {'IHeatBlkT','IHeatBlkTSt'}, ...
      varargin{:} );
