function phcl16ts(varargin);
% phcl16ts( [...] );
% Temps Skin
h = timeplot({'ISk1T','ISk2T','ISk3T'}, ...
      'Temps Skin', ...
      'Skin', ...
      {'ISk1T','ISk2T','ISk3T'}, ...
      varargin{:} );
