function phcl16tmtd(varargin);
% phcl16tmtd( [...] );
% T Mbase T Drift
h = timeplot({'SysTDrift'}, ...
      'T Mbase T Drift', ...
      'T Drift', ...
      {'SysTDrift'}, ...
      varargin{:} );
