function phcl16mkshcff(varargin);
% phcl16mkshcff( [...] );
% MKS H Cl Fl Flow
h = timeplot({'HClFl_Set','HClFl_Flow'}, ...
      'MKS H Cl Fl Flow', ...
      'H Cl Fl Flow', ...
      {'HClFl\_Set','HClFl\_Flow'}, ...
      varargin{:} );
