function phcl16lpvlt(varargin);
% phcl16lpvlt( [...] );
% LPV Laser T
h = timeplot({'ILTE3R3T','Laser_TEC_St'}, ...
      'LPV Laser T', ...
      'Laser T', ...
      {'ILTE3R3T','Laser\_TEC\_St'}, ...
      varargin{:} );
