function phcl16algomps(varargin);
% phcl16algomps( [...] );
% Algo mps
h = timeplot({'raw_climb','climb_rate'}, ...
      'Algo mps', ...
      'mps', ...
      {'raw\_climb','climb\_rate'}, ...
      varargin{:} );
