function phcl16ptrht(varargin);
% phcl16ptrht( [...] );
% PTRH T
h = timeplot({'DACS_T1C','DACS_T2C','ILPV_T1C','ILPV_T2C'}, ...
      'PTRH T', ...
      'T', ...
      {'DACS\_T1C','DACS\_T2C','ILPV\_T1C','ILPV\_T2C'}, ...
      varargin{:} );
