function phcl16tmg(varargin);
% phcl16tmg( [...] );
% T Mbase Gains
h = timeplot({'Pgain','Igain'}, ...
      'T Mbase Gains', ...
      'Gains', ...
      {'Pgain','Igain'}, ...
      varargin{:} );
