function phcl16tr(varargin);
% phcl16tr( [...] );
% Temps Rovers
h = timeplot({'IRv1T','IRv2T','IRv3T','IRv4T'}, ...
      'Temps Rovers', ...
      'Rovers', ...
      {'IRv1T','IRv2T','IRv3T','IRv4T'}, ...
      varargin{:} );
