function phcl16ptrhs(varargin);
% phcl16ptrhs( [...] );
% PTRH Status
h = timeplot({'DACS_PTRHS','DACS_PTRHS','DACS_PTRHS'}, ...
      'PTRH Status', ...
      'Status', ...
      {'DACS\_PTRHS','DACS\_PTRHS','DACS\_PTRHS'}, ...
      varargin{:} );
