function phcl16mkshks(varargin);
% phcl16mkshks( [...] );
% MKS HK Status
h = timeplot({'HClFl_Status'}, ...
      'MKS HK Status', ...
      'Status', ...
      {'HClFl\_Status'}, ...
      varargin{:} );
