function phcl16mkshkstale(varargin);
% phcl16mkshkstale( [...] );
% MKS HK Stale
h = timeplot({'HClFl_Stale','MKS_Stale'}, ...
      'MKS HK Stale', ...
      'Stale', ...
      {'HClFl\_Stale','MKS\_Stale'}, ...
      varargin{:} );
