function phcl16qcli_statflash(varargin);
% phcl16qcli_statflash( [...] );
% QCLI stat flash
h = timeplot({'QCLI_flash'}, ...
      'QCLI stat flash', ...
      'flash', ...
      {'QCLI\_flash'}, ...
      varargin{:} );
