function phcl16ptrhs(varargin);
% phcl16ptrhs( [...] );
% PTRH Status
h = timeplot({'DACS_PTRHS','ILPV_PTRHS','IDPV_PTRHS'}, ...
      'PTRH Status', ...
      'Status', ...
      {'DACS\_PTRHS','ILPV\_PTRHS','IDPV\_PTRHS'}, ...
      varargin{:} );
