function phcl16ti(varargin);
% phcl16ti( [...] );
% Temps Inlet
h = timeplot({'Inlt1T','Inlt2T','Inlt3T','Inlt4T','Inlt5T','Inlt6T'}, ...
      'Temps Inlet', ...
      'Inlet', ...
      {'Inlt1T','Inlt2T','Inlt3T','Inlt4T','Inlt5T','Inlt6T'}, ...
      varargin{:} );
