function phcl16qclimode(varargin);
% phcl16qclimode( [...] );
% QCLI stat mode
h = timeplot({'QCLI_mode'}, ...
      'QCLI stat mode', ...
      'mode', ...
      {'QCLI\_mode'}, ...
      varargin{:} );
