function phcl16pt(varargin);
% phcl16pt( [...] );
% Pumps T
h = timeplot({'Pump1_Cnt_T','Pump2_Cnt_T','Pump1_mot_T','Pump2_mot_T'}, ...
      'Pumps T', ...
      'T', ...
      {'Pump1\_Cnt\_T','Pump2\_Cnt\_T','Pump1\_mot\_T','Pump2\_mot\_T'}, ...
      varargin{:} );
