function phcl16qcli_statrw(varargin);
% phcl16qcli_statrw( [...] );
% QCLI stat rw
h = timeplot({'QCLI_rw'}, ...
      'QCLI stat rw', ...
      'rw', ...
      {'QCLI\_rw'}, ...
      varargin{:} );
