function phcl16cp(varargin);
% phcl16cp( [...] );
% Cell P
h = timeplot({'Cell_P','ICelP','ICelPSt'}, ...
      'Cell P', ...
      'P', ...
      {'Cell\_P','ICelP','ICelPSt'}, ...
      varargin{:} );
