function phcl16pt(varargin);
% phcl16pt( [...] );
% Pumps T
h = timeplot({'Pump1_Head_T','Pump2_Head_T','Pump1_mot_T','Pump2_mot_T'}, ...
      'Pumps T', ...
      'T', ...
      {'Pump1\_Head\_T','Pump2\_Head\_T','Pump1\_mot\_T','Pump2\_mot\_T'}, ...
      varargin{:} );
