function phcl16powers(varargin);
% phcl16powers( [...] );
% Power Status
h = ne_dstat({
  'PM0I1_S', 'PM0Stat', 0; ...
	'PM0I2_S', 'PM0Stat', 2; ...
	'PM0TO_S', 'PM0Stat', 4; ...
	'PM0V1_S', 'PM0Stat', 1; ...
	'PM0V2_S', 'PM0Stat', 3; ...
	'PM1TO_S', 'PM1Stat', 4; ...
	'PmpsIS', 'PM1Stat', 0; ...
	'PmpsVS', 'PM1Stat', 1 }, 'Status', varargin{:} );
