function phcl16qcliflash(varargin);
% phcl16qcliflash( [...] );
% QCLI stat flash
h = timeplot({'QCLI_flash'}, ...
      'QCLI stat flash', ...
      'flash', ...
      {'QCLI\_flash'}, ...
      varargin{:} );
