function phcl16qclis(varargin);
% phcl16qclis( [...] );
% QCLI stat Stale
h = timeplot({'QCLI_Stale','SSP_Stale'}, ...
      'QCLI stat Stale', ...
      'Stale', ...
      {'QCLI\_Stale','SSP\_Stale'}, ...
      varargin{:} );
