function phcl16idpvt(varargin);
% phcl16idpvt( [...] );
% IDPV T
h = timeplot({'IDPV_T1C','IDPV_T2C'}, ...
      'IDPV T', ...
      'T', ...
      {'IDPV\_T1C','IDPV\_T2C'}, ...
      varargin{:} );
