function phcl16gdpsig(varargin);
% phcl16gdpsig( [...] );
% Gas Deck PSIG
h = timeplot({'GasHP','GasLP'}, ...
      'Gas Deck PSIG', ...
      'PSIG', ...
      {'GasHP','GasLP'}, ...
      varargin{:} );
