function phcl16ptrhrh(varargin);
% phcl16ptrhrh( [...] );
% PTRH RH
h = timeplot({'DACS_RHC','ILPV_RHC'}, ...
      'PTRH RH', ...
      'RH', ...
      {'DACS\_RHC','ILPV\_RHC'}, ...
      varargin{:} );
