function phcl16ps(varargin);
% phcl16ps( [...] );
% Pumps Status
h = ne_dstat({
  'OVF1', 'Ct0Stat', 4; ...
	'OVF2', 'Ct0Stat', 5; ...
	'L2Stat', 'Ct0Stat', 14; ...
	'Resynch', 'Ct0Stat', 15 }, 'Status', varargin{:} );
