function phcl16mkshkack2(varargin);
% phcl16mkshkack2( [...] );
% MKS HK ACK2
h = timeplot({'HClFl_ACK2'}, ...
      'MKS HK ACK2', ...
      'ACK2', ...
      {'HClFl\_ACK2'}, ...
      varargin{:} );
