function phcl16gdf(varargin);
% phcl16gdf( [...] );
% Gas Deck Flow
h = timeplot({'GasFl','GsFlSt'}, ...
      'Gas Deck Flow', ...
      'Flow', ...
      {'GasFl','GsFlSt'}, ...
      varargin{:} );
