function phcl16dacst(varargin);
% phcl16dacst( [...] );
% DACS T
h = timeplot({'vl_cpuT','vl_bdT','DACS_T1C','DACS_T2C'}, ...
      'DACS T', ...
      'T', ...
      {'vl\_cpuT','vl\_bdT','DACS\_T1C','DACS\_T2C'}, ...
      varargin{:} );
