function phcl16qclififodep(varargin);
% phcl16qclififodep( [...] );
% QCLI stat fifodep
h = timeplot({'QCLI_fifodep'}, ...
      'QCLI stat fifodep', ...
      'fifodep', ...
      {'QCLI\_fifodep'}, ...
      varargin{:} );
